swipe:
  4:
    down:
      command: "awesome-client 'awful.tag.viewnext()'"
      #command: "awesome-client 'require(\"revelation\")()'"
    up:
      #command: "awesome-client 'awful.tag.viewprev()'"
      command: "awesome-client 'require(\"revelation\")()'"
    left:
      command: "xdotool key alt+Right" 
    right:
      command: "xdotool key alt+Left"
  3:
    down:
      command: "awesome-client 'awful.client.focus.byidx(1)'"
    up:
      command: "awesome-client 'awful.client.focus.byidx(-1)'"

threshold:
  swipe: 0.4
  pinch: 0.4

interval:
  swipe: 0.8
  pinch: 0.1
