swipe:
  4:
    down:
      window:
        maximized: remove
    up:
      window:
        maximized: add
    left:
      command: "xdotool key alt+Left" 
    right:
      command: "xdotool key alt+Right"
  3:
    left:
      sendkey: "LEFTALT+LEFT" # history back
    right:
      sendkey: "LEFTALT+RIGHT" # history forward
    down:
    up:

threshold:
  swipe: 0.4
  pinch: 0.4

interval:
  swipe: 0.8
  pinch: 0.1
