swipe:
  4:
    down:
      command: "i3-msg 'workspace next'"
    up:
      command: "i3-msg 'workspace prev'"
    left:
      command: "xdotool key alt+Right" 
    right:
      command: "xdotool key alt+Left"

threshold:
  swipe: 0.4
  pinch: 0.4

interval:
  swipe: 0.8
  pinch: 0.1
